services:
  rstudio:
    container_name: rstudio
    image: rocker/geospatial
    ports:
      - "8787:8787"
    volumes:
      - ./workspace:/home/rstudio/workspace
    environment:
      - DISABLE_AUTH=true

